export const oneTime = [
  {
    amount: 5,
    perk: "$5-$25 Perks",
    subPerk: "Ami",
    benifits: ["Ami Sticker", "100% Tax Deductible"],
  },
  {
    amount: 10,
    perk: "$5-$25 Perks",
    subPerk: "Ami",
    benifits: ["Ami Sticker", "100% Tax Deductible"],
  },
  {
    amount: 15,
    perk: "$5-$25 Perks",
    subPerk: "Ami",
    benifits: ["Ami Sticker", "100% Tax Deductible"],
  },
  {
    amount: 20,
    perk: "$5-$25 Perks",
    subPerk: "Ami",
    benifits: ["Ami Sticker", "100% Tax Deductible"],
  },
  {
    amount: 25,
    perk: "$5-$25 Perks",
    subPerk: "Ami",
    benifits: ["Ami Sticker", "100% Tax Deductible"],
  },
  {
    amount: 50,
    perk: "$50 Perks",
    subPerk: "Bon",
    benifits: [
      "Ami Sticker",
      "Ami T-Shirt",
      "10% discount on all Festival Merch",
      "100% Tax Deductible",
    ],
  },
  {
    amount: 100,
    perk: "$100 Perks",
    subPerk: "Grand",
    benifits: [
      "Ami Sticker",
      "Ami T-Shirt",
      "10% discount on all Festival Merch",
      "Tax deductible less $50",
      "Lagniappe Pass",
      "Listing on Festival website",
    ],
  },
  {
    amount: 250,
    perk: "$250 Perks",
    subPerk: "Tres Bon ",
    benifits: [
      "Ami Sticker",
      "10% discount on all Festival Merch",
      "Tax deductible less $100",
      "2 Lagniappe Passes",
      "Listing on Festival website",
    ],
  },
  {
    amount: 500,
    perk: "$500 Perks",
    subPerk: "Magnifique",
    benifits: [
      "Ami Sticker",
      "Ami T-Shirt",
      "10% discount on all Festival Merch",
      "Tax deductible less $100",
      "2 Bon Temp Passes",
      "Listing on Festival website",
      "Listing on Official Festival guide",
      "Recognition during Festival International 2023",
      "Festival Pin",
      "Festival Poster",
    ],
  },
];

export const monthly = [
  {
    amount: 5,
    perk: "$5 Perks",
    subPerk: "Bon",
    benifits: [
      "Ami Sticker",
      "Ami T-Shirt",
      "10% discount on all Festival Merch",
      "100% Tax Deductible",
    ],
  },
  {
    amount: 15,
    perk: "$15 Perks",
    subPerk: "Grand",
    benifits: [
      "Ami Sticker",
      "Ami T-Shirt",
      "10% discount on all Festival Merch",
      "Tax deductible less $50",
      "Lagniappe Pass",
      "Listing on Festival website",
    ],
  },
  {
    amount: 30,
    perk: "$30 Perks",
    subPerk: "Tres Bon",
    benifits: [
      "Ami Sticker",
      "10% discount on all Festival Merch",
      "Tax deductible less $100",
      "2 Lagniappe Passes",
      "Listing on Festival website",
    ],
  },
  {
    amount: 50,
    perk: "$50 Perks",
    subPerk: "Magnifique",
    benifits: [
      "Ami Sticker",
      "Ami T-Shirt",
      "10% discount on all Festival Merch",
      "Tax deductible less $100",
      "2 Bon Temp Passes",
      "Listing on Festival website",
      "Listing on Official Festival guide",
      "Recognition during Festival International 2023",
      "Festival Pin",
      "Festival Poster",
    ],
  },
];

export const annually = [
  {
    amount: 50,
    perk: "$50 Perks",
    subPerk: "Bon",
    benifits: [
      "Ami Sticker",
      "Ami T-Shirt",
      "10% discount on all Festival Merch",
      "10% discount on Festival passes",
      "100% Tax Deductible",
    ],
  },
  {
    amount: 100,
    perk: "$100 Perks",
    subPerk: "Grand",
    benifits: [
      "Ami Sticker",
      "Ami T-Shirt",
      "10% discount on all Festival Merch",
      "Tax deductible less $50",
      "Lagniappe Pass",
      "Listing on Festival website",
    ],
  },
  {
    amount: 250,
    perk: "$250 Perks",
    subPerk: "Très Bon Ami",
    benifits: [
      "Ami Sticker",
      "Ami T-Shirt",
      "10% discount on all Festival Merch",
      "Tax deductible less $100",
      "2 Lagniappe Passes",
      "Listing on Festival website & in Festival Guide",
      "Stage recognition during Festival 2022",
    ],
  },
  {
    amount: 500,
    perk: "$500 Perks",
    subPerk: "Magnifique Ami",
    benifits: [
      "Ami Sticker",
      "Ami T-Shirt",
      "10% discount on all Festival Merch",
      "10% discount on Festival passes",
      "Tax deductible less $100",
      "2022 Poster",
      "2022 Pin",
      "Stage recognition during Festival 2022",
      "Listing on Festival Website and in Festival Guide",
    ],
  },
];
